// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TEMPORARY WORKAROUND: Fallback values for production deployment
// TODO: Configure these as environment variables in Lovable Cloud instead
// WARNING: These are public keys (safe to expose) but should ideally come from env vars
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qltfylleiwjvtngmsdyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdGZ5bGxlaXdqdnRuZ21zZHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMTE4NDcsImV4cCI6MjA3NTU4Nzg0N30.F5OwZaagDXjj1mZP0rYouyQ3idJuSzZB0B5sLWHS3-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});